
import java.awt.event.KeyEvent;

/**
 * @author Vincenzo Scarso
 */
public class Calcolatrice extends javax.swing.JFrame {

    private Boolean after_equal = false;
    private History History = new History("cronologia.txt");

    public Calcolatrice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoDialog = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        buttonClear = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonPercentage = new javax.swing.JButton();
        buttonDivide = new javax.swing.JButton();
        buttonSeven = new javax.swing.JButton();
        buttonEight = new javax.swing.JButton();
        buttonNine = new javax.swing.JButton();
        buttonMultiply = new javax.swing.JButton();
        buttonFour = new javax.swing.JButton();
        buttonFive = new javax.swing.JButton();
        buttonSix = new javax.swing.JButton();
        buttonSubtract = new javax.swing.JButton();
        buttonOne = new javax.swing.JButton();
        buttonTwo = new javax.swing.JButton();
        buttonThree = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        buttonChangeSymbol = new javax.swing.JButton();
        buttonZero = new javax.swing.JButton();
        buttonPeriod = new javax.swing.JButton();
        buttonEquals = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        saveHistoryMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        infoMenuItem = new javax.swing.JMenuItem();

        infoDialog.setBackground(new java.awt.Color(0, 204, 204));
        infoDialog.setFocusable(false);
        infoDialog.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        infoDialog.setName("Info"); // NOI18N
        infoDialog.setResizable(false);
        infoDialog.setSize(new java.awt.Dimension(280, 110));
        infoDialog.setType(java.awt.Window.Type.UTILITY);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setText("Calcolatrice.java | v1.0");
        jPanel7.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("Vincenzo Scarso");
        jPanel7.add(jLabel2);

        infoDialog.getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);
        infoDialog.getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);
        infoDialog.getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);
        infoDialog.getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);
        infoDialog.getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_START);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcolatrice");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        setMinimumSize(new java.awt.Dimension(303, 361));
        setPreferredSize(new java.awt.Dimension(261, 371));
        setResizable(false);
        setSize(new java.awt.Dimension(261, 371));

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setToolTipText("esegui un calcolo...");
        jTextField2.setAlignmentX(0.0F);
        jTextField2.setAlignmentY(0.0F);
        jTextField2.setFocusable(false);
        jPanel2.add(jTextField2);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.setHighlighter(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(5, 4, 3, 3));

        buttonClear.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonClear.setText("C");
        buttonClear.setFocusable(false);
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel1.add(buttonClear);

        buttonDelete.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonDelete.setText("←");
        buttonDelete.setFocusable(false);
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(buttonDelete);

        buttonPercentage.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonPercentage.setText("%");
        buttonPercentage.setFocusable(false);
        buttonPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPercentageActionPerformed(evt);
            }
        });
        jPanel1.add(buttonPercentage);

        buttonDivide.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonDivide.setText("÷");
        buttonDivide.setFocusable(false);
        buttonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivideActionPerformed(evt);
            }
        });
        jPanel1.add(buttonDivide);

        buttonSeven.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonSeven.setText("7");
        buttonSeven.setFocusable(false);
        buttonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSevenActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSeven);

        buttonEight.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonEight.setText("8");
        buttonEight.setFocusable(false);
        buttonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEightActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEight);

        buttonNine.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonNine.setText("9");
        buttonNine.setFocusable(false);
        buttonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNineActionPerformed(evt);
            }
        });
        jPanel1.add(buttonNine);

        buttonMultiply.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonMultiply.setText("x");
        buttonMultiply.setFocusable(false);
        buttonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplyActionPerformed(evt);
            }
        });
        jPanel1.add(buttonMultiply);

        buttonFour.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonFour.setText("4");
        buttonFour.setFocusable(false);
        buttonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFourActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFour);

        buttonFive.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonFive.setText("5");
        buttonFive.setFocusable(false);
        buttonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiveActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFive);

        buttonSix.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonSix.setText("6");
        buttonSix.setFocusable(false);
        buttonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSixActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSix);

        buttonSubtract.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonSubtract.setText("-");
        buttonSubtract.setFocusable(false);
        buttonSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubtractActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSubtract);

        buttonOne.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonOne.setText("1");
        buttonOne.setFocusable(false);
        buttonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOneActionPerformed(evt);
            }
        });
        jPanel1.add(buttonOne);

        buttonTwo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonTwo.setText("2");
        buttonTwo.setFocusable(false);
        buttonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwoActionPerformed(evt);
            }
        });
        jPanel1.add(buttonTwo);

        buttonThree.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonThree.setText("3");
        buttonThree.setFocusable(false);
        buttonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThreeActionPerformed(evt);
            }
        });
        jPanel1.add(buttonThree);

        buttonAdd.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonAdd.setText("+");
        buttonAdd.setFocusable(false);
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        jPanel1.add(buttonAdd);

        buttonChangeSymbol.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonChangeSymbol.setText("+/-");
        buttonChangeSymbol.setToolTipText("");
        buttonChangeSymbol.setFocusable(false);
        buttonChangeSymbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeSymbolActionPerformed(evt);
            }
        });
        jPanel1.add(buttonChangeSymbol);

        buttonZero.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonZero.setText("0");
        buttonZero.setFocusable(false);
        buttonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZeroActionPerformed(evt);
            }
        });
        jPanel1.add(buttonZero);

        buttonPeriod.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonPeriod.setText(".");
        buttonPeriod.setFocusable(false);
        buttonPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPeriodActionPerformed(evt);
            }
        });
        jPanel1.add(buttonPeriod);

        buttonEquals.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        buttonEquals.setText("=");
        buttonEquals.setFocusable(false);
        buttonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqualsActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEquals);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jMenuBar1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        jMenu1.setText("File");

        saveHistoryMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S,
                java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveHistoryMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/history.png"))); // NOI18N
        saveHistoryMenuItem.setText("Salva...");
        saveHistoryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveHistoryMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveHistoryMenuItem);
        jMenu1.add(jSeparator1);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4,
                java.awt.event.InputEvent.ALT_DOWN_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/exit.png"))); // NOI18N
        exitMenuItem.setText("Esci");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Altro");

        infoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I,
                java.awt.event.InputEvent.CTRL_DOWN_MASK));
        infoMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/info.png"))); // NOI18N
        infoMenuItem.setText("Info");
        infoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(infoMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleDescription("Una semplice calcolatrice scritta realizzata in java");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonClearActionPerformed
        jTextField1.setText("0");
        jTextField2.setText("");
        after_equal = false;
    }// GEN-LAST:event_buttonClearActionPerformed

    private void buttonZeroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonZeroActionPerformed
        appendCharacter("0");
    }// GEN-LAST:event_buttonZeroActionPerformed

    private void buttonOneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonOneActionPerformed
        appendCharacter("1");
    }// GEN-LAST:event_buttonOneActionPerformed

    private void buttonTwoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonTwoActionPerformed
        appendCharacter("2");
    }// GEN-LAST:event_buttonTwoActionPerformed

    private void buttonThreeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonThreeActionPerformed
        appendCharacter("3");
    }// GEN-LAST:event_buttonThreeActionPerformed

    private void buttonFourActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonFourActionPerformed
        appendCharacter("4");
    }// GEN-LAST:event_buttonFourActionPerformed

    private void buttonFiveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonFiveActionPerformed
        appendCharacter("5");
    }// GEN-LAST:event_buttonFiveActionPerformed

    private void buttonSixActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonSixActionPerformed
        appendCharacter("6");
    }// GEN-LAST:event_buttonSixActionPerformed

    private void buttonSevenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonSevenActionPerformed
        appendCharacter("7");
    }// GEN-LAST:event_buttonSevenActionPerformed

    private void buttonEightActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonEightActionPerformed
        appendCharacter("8");
    }// GEN-LAST:event_buttonEightActionPerformed

    private void buttonNineActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonNineActionPerformed
        appendCharacter("9");
    }// GEN-LAST:event_buttonNineActionPerformed

    private void buttonPeriodActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonPeriodActionPerformed
        appendCharacter(".");
    }// GEN-LAST:event_buttonPeriodActionPerformed

    private void buttonEqualsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonEqualsActionPerformed
        if (!jTextField2.getText().equals("")) {
            calculateAndUpdateTextFields(0, "=");
            after_equal = true;
        }
    }// GEN-LAST:event_buttonEqualsActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonAddActionPerformed
        calculateAndUpdateTextFields(1, "+");
        after_equal = false;
    }// GEN-LAST:event_buttonAddActionPerformed

    private void buttonSubtractActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonSubtractActionPerformed
        calculateAndUpdateTextFields(1, "-");
        after_equal = false;
    }// GEN-LAST:event_buttonSubtractActionPerformed

    private void buttonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonMultiplyActionPerformed
        calculateAndUpdateTextFields(1, "*");
        after_equal = false;
    }// GEN-LAST:event_buttonMultiplyActionPerformed

    private void buttonDivideActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonDivideActionPerformed
        calculateAndUpdateTextFields(1, "÷");
        after_equal = false;
    }// GEN-LAST:event_buttonDivideActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonDeleteActionPerformed
        String main_display_content = jTextField1.getText();
        int length = main_display_content.length();
        String updated_string = main_display_content.substring(0, length - 1);

        if (updated_string.equals("")) {
            jTextField1.setText("0");
        } else {
            jTextField1.setText(updated_string);
        }
    }// GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonPercentageActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonPercentageActionPerformed
        calculateAndUpdateTextFields(1, "%");
        after_equal = false;
    }// GEN-LAST:event_buttonPercentageActionPerformed

    private void buttonChangeSymbolActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonChangeSymbolActionPerformed
        String main_display_content = jTextField1.getText();
        String left_operator = main_display_content.substring(0, 1);
        String temp = main_display_content;
        int main_display_length = main_display_content.length();

        if (!main_display_content.equals("0")) {

            if (left_operator.equals("-")) {
                main_display_content = main_display_content.substring(1, main_display_length);
            } else {
                main_display_content = "-" + temp;
            }
        }

        jTextField1.setText(main_display_content);
    }// GEN-LAST:event_buttonChangeSymbolActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField1KeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_NUMPAD0:
                buttonZero.doClick();
                break;
            case KeyEvent.VK_NUMPAD1:
                buttonOne.doClick();
                break;
            case KeyEvent.VK_NUMPAD2:
                buttonTwo.doClick();
                break;
            case KeyEvent.VK_NUMPAD3:
                buttonThree.doClick();
                break;
            case KeyEvent.VK_NUMPAD4:
                buttonFour.doClick();
                break;
            case KeyEvent.VK_NUMPAD5:
                buttonFive.doClick();
                break;
            case KeyEvent.VK_NUMPAD6:
                buttonSix.doClick();
                break;
            case KeyEvent.VK_NUMPAD7:
                buttonSeven.doClick();
                break;
            case KeyEvent.VK_NUMPAD8:
                buttonEight.doClick();
                break;
            case KeyEvent.VK_NUMPAD9:
                buttonNine.doClick();
                break;
            case KeyEvent.VK_ADD:
                buttonAdd.doClick();
                break;
            case KeyEvent.VK_SUBTRACT:
                buttonSubtract.doClick();
                break;
            case KeyEvent.VK_MULTIPLY:
                buttonMultiply.doClick();
                break;
            case KeyEvent.VK_DIVIDE:
                buttonDivide.doClick();
                break;
            case KeyEvent.VK_DECIMAL:
                buttonPeriod.doClick();
                break;
            case KeyEvent.VK_BACK_SPACE:
                buttonDelete.doClick();
                break;
            case KeyEvent.VK_C:
                buttonClear.doClick();
                break;
            case KeyEvent.VK_ENTER:
                buttonEquals.doClick();
                break;
        }
    }// GEN-LAST:event_jTextField1KeyPressed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitMenuItemActionPerformed
        History.freeResources();
        System.exit(0);
    }// GEN-LAST:event_exitMenuItemActionPerformed

    private void saveHistoryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveHistoryMenuItemActionPerformed
        History.saveHistoryToFile();
    }// GEN-LAST:event_saveHistoryMenuItemActionPerformed

    private void infoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_infoMenuItemActionPerformed
        infoDialog.setVisible(true);
    }// GEN-LAST:event_infoMenuItemActionPerformed

    private void appendCharacter(String character) {
        String main_display_content = jTextField1.getText();

        if (after_equal) {
            jTextField1.setText(character);
            jTextField2.setText("");
            after_equal = false;
        } else if (character.equals(".") && !main_display_content.contains(".")) {
            jTextField1.setText(main_display_content + character);
        } else if (character.equals(".") && main_display_content.contains(".")) {
            // non fa nulla
        } else if (main_display_content.equals("0")) {
            jTextField1.setText(character);
        } else {
            jTextField1.setText(main_display_content + character);
        }
    }

    private void calculateAndUpdateTextFields(int result_destination, String key_pressed_operator) {
        TextFields TF = new TextFields(jTextField1.getText(), jTextField2.getText());
        Results R;

        if (TF.secondary_display_content.equals("")) {
            TF.main_display_content = parenthesisInator(TF.main_display_content);
            jTextField2.setText(TF.main_display_content + key_pressed_operator);
            jTextField1.setText("0");
        } else {
            R = handleOperation(TF, result_destination);

            if (result_destination == 0 && "=".equals(key_pressed_operator)) {
                updateTextFieldsWithResultOnMainDisplay(TF, R);
            } else {
                updateTextFieldsWithResultOnSecondaryDisplay(TF, R, key_pressed_operator);
            }

            jTextField1.setText(TF.main_display_content);
            jTextField2.setText(TF.secondary_display_content);

            History.saveToBuffer(R.first_value + R.OP.middle_operator + R.second_value + "=" + R.result);
        }
    }

    private void updateTextFieldsWithResultOnMainDisplay(TextFields TF, Results R) {
        String temp;

        if (after_equal) {
            R.first_value = parenthesisInator(R.first_value);
            R.second_value = parenthesisInator(R.second_value);
        } else {
            temp = R.first_value;
            R.first_value = parenthesisInator(R.second_value);
            R.second_value = parenthesisInator(temp);
        }

        TF.secondary_display_content = R.first_value + R.OP.middle_operator + R.second_value;
        TF.main_display_content = R.result;
    }

    private void updateTextFieldsWithResultOnSecondaryDisplay(TextFields TF, Results R, String key_pressed_operator) {
        if (R.OP.middle_operator_position == TF.secondary_display_content.length() - 1) { // quando è presente un solo
                                                                                          // valore nel campo di testo
                                                                                          // secondario
            TF.secondary_display_content = TF.secondary_display_content.substring(0, R.OP.middle_operator_position);
            TF.secondary_display_content += key_pressed_operator;
            TF.main_display_content = "0";
        } else if (after_equal) {
            TF.secondary_display_content = TF.main_display_content + key_pressed_operator;
            TF.main_display_content = "0";
        } else {
            R.first_value = parenthesisInator(R.first_value);
            R.second_value = parenthesisInator(R.second_value);

            TF.secondary_display_content = R.second_value + key_pressed_operator;
            TF.main_display_content = "0";
        }
    }

    private Results handleOperation(TextFields TF, int result_destination) {
        TF.secondary_display_content = deParenthesisInator(TF.secondary_display_content);
        MiddleOperator OP = new MiddleOperator(TF.secondary_display_content); // ottengo l'operatore tra i due numeri

        double main_display_value = Double.parseDouble(TF.main_display_content);
        double secondary_display_value;
        double result = 0;

        if (result_destination == 0) { // destinazione del risultato nel main display
            if (after_equal) {
                TF.secondary_display_content = TF.secondary_display_content.substring(OP.middle_operator_position + 1,
                        TF.secondary_display_content.length()); // prendo solo la parte dopo l'operatore
                secondary_display_value = Double.parseDouble(TF.secondary_display_content);
                result = calculate(OP.middle_operator, main_display_value, secondary_display_value);
            } else {
                TF.secondary_display_content = TF.secondary_display_content.substring(0, OP.middle_operator_position); // rimuovo
                                                                                                                       // l'operatore
                                                                                                                       // dal
                                                                                                                       // contenuto
                                                                                                                       // della
                                                                                                                       // stringa
                secondary_display_value = Double.parseDouble(TF.secondary_display_content);
                result = calculate(OP.middle_operator, secondary_display_value, main_display_value);
            }
        } else { // destinazione del risultato nel secondary display
            TF.secondary_display_content = TF.secondary_display_content.substring(0, OP.middle_operator_position); // rimuovo
                                                                                                                   // l'operatore
                                                                                                                   // dal
                                                                                                                   // contenuto
                                                                                                                   // della
                                                                                                                   // stringa
            secondary_display_value = Double.parseDouble(TF.secondary_display_content);
            secondary_display_value = calculate(OP.middle_operator, secondary_display_value, main_display_value);
        }

        return new Results(main_display_value, secondary_display_value, OP, result);
    }

    // metodo che aggiunge le parentesi al valore se ha segno negativo:
    private String parenthesisInator(String str_value) {
        String left_operator = str_value.substring(0, 1);

        if (left_operator.equals("-")) {
            str_value = "(" + str_value + ")";
        }

        return str_value;
    }

    // metodo che rimuove le parentesi al valore se presenti:
    private String deParenthesisInator(String str_value) {

        if (str_value.contains("(") || str_value.contains(")")) {
            str_value = str_value.replace("(", "");
            str_value = str_value.replace(")", "");
        }

        return str_value;
    }

    private double calculate(String operator, double first_value, double second_value) {
        switch (operator) {
            case "+":
                return first_value + second_value;
            case "-":
                return first_value - second_value;
            case "*":
                return first_value * second_value;
            case "÷":
                return first_value / second_value;
            case "%":
                return (first_value * second_value) / 100;
            default:
                System.out.println("[ERRORE]: Operatore non riconosciuto");
                return 0;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcolatrice.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calcolatrice().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonChangeSymbol;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonDivide;
    private javax.swing.JButton buttonEight;
    private javax.swing.JButton buttonEquals;
    private javax.swing.JButton buttonFive;
    private javax.swing.JButton buttonFour;
    private javax.swing.JButton buttonMultiply;
    private javax.swing.JButton buttonNine;
    private javax.swing.JButton buttonOne;
    private javax.swing.JButton buttonPercentage;
    private javax.swing.JButton buttonPeriod;
    private javax.swing.JButton buttonSeven;
    private javax.swing.JButton buttonSix;
    private javax.swing.JButton buttonSubtract;
    private javax.swing.JButton buttonThree;
    private javax.swing.JButton buttonTwo;
    private javax.swing.JButton buttonZero;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JDialog infoDialog;
    private javax.swing.JMenuItem infoMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenuItem saveHistoryMenuItem;
    // End of variables declaration//GEN-END:variables
}
